app:
  name: "Image Generation API"

providers:
  dalle:
    api_url: "https://api.openai.com/v1/images/generations"
    api_version: "v1"
    default_model: "dall-e-3"
    timeout: 30
    max_retries: 3
    retry_delay: 1

  midjourney:
    api_url: "http://localhost:8080"
    timeout: 60
    max_retries: 3
    retry_delay: 2
    poll_timeout: 300
    poll_interval: 10

request:
  timeout: 30
  max_retries: 3
  retry_delay: 1 
