version: "0.2"
language: en
words:
  - aiohttp
  - dalle
  - dotenv
  - fastapi
  - midjourney
  - openai
  - openrouter
  - pydantic
  - uvicorn
ignorePaths:
  - node_modules
  - venv
  - .git
  - .vscode
  - __pycache__
  - "*.pyc"
dictionaries:
  - python
  - typescript
  - en_US
allowCompoundWords: true
