version: "0.2"
language: en
words:
  - aiohttp
  - asyncio
  - DALL
  - dotenv
  - fastapi
  - mypy
  - pydantic
  - pytest
  - ruff
  - uvicorn
ignorePaths:
  - .git
  - .venv
  - __pycache__
  - build
  - dist
  - "*.pyc"
dictionaries:
  - python
  - typescript
  - en_US
allowCompoundWords: true
